### ISSUE TITLE
The Article is shown in the wrong part of the documentation 

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/docs-v7#1014] opened 2017-12-18 12:16 UTC
An Angular article is shown in the non-Angular part of the docs. - https://docs.nativescript.org/core-concepts/angular-navigation 
![screenshot 44](https://user-images.githubusercontent.com/17448734/34105625-c3dc1bba-e3fd-11e7-97b8-700f19d16a35.png)

**Comment by etabakov** [comment] 2018-02-23 12:27
Closing as duplicate of https://github.com/NativeScript/docs/issues/1018

**Closed as completed by etabakov** 2018-02-23 12:27 UTC
