### ISSUE TITLE
Viewport exceeds display's size on android

### ISSUE THREAD

**Issue by marco-gagliardi** [NativeScript/docs-v7#804] opened 2017-06-16 09:11 UTC
I've followed the Grocery app Tutorial (and I think I didn't make any mistake).
There is a display problem  on Android, where the app doesn't seem to fit correctly the display frame. 
As you can see in this screenshot the login background image doesn't cover the whole page (there's a sort of repeat-y going on).
![schermata 2017-06-15 alle 17 05 54](https://user-images.githubusercontent.com/2972151/27220095-33a5b46c-5284-11e7-9491-057f82fdf005.png)
In this screenshot you can see how the list exceeds the vertical size too. Even if you scroll down to the bottom of the list there are one item and a half not visible.

![schermata 2017-06-15 alle 17 06 09](https://user-images.githubusercontent.com/2972151/27220149-70c7e78e-5284-11e7-91c1-3b982e57578d.png)

**Comment by marco-gagliardi** [comment] 2017-06-19 09:27
Just to investigate the problem further, I've extended the app and added a new page (containing a google-maps plugin) and the problem seems to propagate to any Activity. (look at the controls at the bottom of the page)

M

![schermata 2017-06-15 alle 17 08 53](https://user-images.githubusercontent.com/2972151/27278555-017906e6-54e2-11e7-8f59-e5c0d0b38b20.png)

**Comment by marco-gagliardi** [comment] 2017-06-21 08:14
I've just cloned the clean tutorial project straight from this repo and started it in the emulator. It seems it's affected by the same issue.

Here the list has reached the full viewport height due to his size
![schermata 2017-06-21 alle 09 53 07](https://user-images.githubusercontent.com/2972151/27373871-28aa20cc-566a-11e7-8009-856150fab36b.png)

here is what happens when I add one more item and scroll down to the bottom of the page. Item 1 cannot be seen.

![schermata 2017-06-21 alle 09 53 27](https://user-images.githubusercontent.com/2972151/27373910-49af9860-566a-11e7-84ac-9de3d70d8d22.png)

**Comment by tjvantoll** [comment] 2017-06-26 17:58
Hi @marco-gagliardi,

This is an odd one. I just ran through the tutorial myself and I’m not seeing this problem. Are you seeing this in apps other than Groceries? For example, could you try `tns create TestApp --ng`, `cd TestApp`, `tns run android` and see if you’re having the same problems?

**Comment by marco-gagliardi** [comment] 2017-06-27 16:09
Hi @tjvantoll ,

actually no, I haven't experienced this issue with other apps, not either in one I'm developing on my own. I can also tell you that Groceries app seems to be affected by the same issue even when running on my real device. Here is a screenshot: 
![screenshot_20170627-180345](https://user-images.githubusercontent.com/2972151/27597716-7b50c7ce-5b63-11e7-9b20-e9b9e17e1343.png)

I promise there is an item called "1" in the list, and the scrollbar has reached the bottom of the page! Again, as in the emulator, the device is a Nexus5x. Might this issue be related to the code applied to the status bar?

**Comment by tjvantoll** [comment] 2017-06-27 19:56
Thanks @marco-gagliardi,

Interesting. It’s definitely possible that the status bar code is affecting the layout, but I don’t know. I’m having some trouble recreating this, so let me check with a few others and get back with you.

**Comment by tjvantoll** [comment] 2017-06-27 20:10
Ok I got it this time when I tried a Nexus 5X. Odd. I’m moving this bug over to the main Groceries repo and I’ll take a look https://github.com/NativeScript/sample-Groceries/issues/260. Thanks for reporting this! And if you find a root cause please let me know.

**Closed as completed by tjvantoll** 2017-06-27 20:10 UTC
