### ISSUE TITLE
Broken API Reference Links on NS Vue Article

### ISSUE THREAD

**Issue by AngeloAnolin** [NativeScript/docs-v7#1848] opened 2019-11-26 00:34 UTC
In this article page (and some other Vue-specific pages), I am finding that the links to the API Reference for the component is broken or cannot be found.

Article Link:
https://docs.nativescript.org/vuejs/ns-ui/Calendar/overview

API Reference Link:
https://docs.nativescript.org/vuejs/ns-ui-api-reference/classes/radcalendarcomponent

The API Reference link can be found on the following:
- API Reference Links (On the Bottom Right Hand side of the Page)
- RadCalendar Component Link (Bottom of the Page)
- All RadCalendar Link that points to the API Reference Link mentioned above

**Comment by NickIliev** [comment] 2019-12-04 14:25
@AngeloAnolin thank you for reporting the issue. This one will be fixed when[ this PR is merged](https://github.com/NativeScript/docs/pull/1849) and the new docs are published (within few days).

As a temporary solution remove the **viewjs/** from the generated link to open the wanted API resources.

For example:
https://docs.nativescript.org/ns-ui-api-reference/classes/radcalendarcomponent

**Comment by NickIliev** [comment] 2019-12-06 08:39
the issue is now fixed via https://github.com/NativeScript/docs/pull/1849 and the documentation update is live

**Closed as completed by NickIliev** 2019-12-06 08:39 UTC
