### ISSUE TITLE
add "tns install" to the CLI documentation

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/docs-v7#470] opened 2016-08-04 10:04 UTC
_From @psnider on August 3, 2016 16:37_

 The list of CLI commands is missing _install_
https://github.com/NativeScript/nativescript-cli#the-commands

_Copied from original issue: NativeScript/nativescript-cli#1978_

**Comment by tjvantoll** [comment] 2016-08-04 14:20
This could be considered a duplicate of https://github.com/NativeScript/docs/issues/157.

Overall I’d love to see a single article on the {N} docs, probably under Core Concepts, that introduced the NativeScript CLI, talked about the common things you do with it, and pointed people at the CLI GitHub repo’s README for further details.

**Comment by etabakov** [comment] 2018-02-08 13:55
Will be resolved by https://github.com/NativeScript/docs/issues/157

**Comment by etabakov** [comment] 2018-02-27 11:29
The [documentation of the CLI](https://docs.nativescript.org/docs-cli/start) is now part of docs.nativescript.org. This includes an article for [tns install](https://docs.nativescript.org/docs-cli/project/configuration/install).

**Closed as completed by etabakov** 2018-02-27 11:29 UTC
Labels: help wanted, in progress
