### ISSUE TITLE
Examples not showing up on 'platform' cookbook in docs.nativescript.org

### ISSUE THREAD

**Issue by anthonytietjen** [NativeScript/docs-v7#467] opened 2016-07-31 00:25 UTC
The examples aren't showing up here:
https://docs.nativescript.org/cookbook/platform

I tried on Safari and Chrome for OS X El Capitan.

**Comment by tjvantoll** [comment] 2016-08-01 15:54
Thanks @tones411! Closing this as a duplicate of #378, and just fyi some big improvements are coming to the cookbook soon 😄

**Closed as completed by tjvantoll** 2016-08-01 15:54 UTC
