### ISSUE TITLE
"Extend your existing iOS app with Angular 2 and NativeScript" article outdated info

### ISSUE THREAD

**Issue by georgij** [NativeScript/docs-v7#720] opened 2017-04-04 14:18 UTC
I can't find TNSWidgets.framework and ./metadata-generation-build-step.

**Comment by NickIliev** [comment] 2017-04-06 11:39
@georgij the article is outdated as in the current state NativeScript CLI is not bringing TNSWidgets.framweork to the **platforms** folder at all. In the current state this framework file is taken directly from the **node_modules** folder (as part of the tns-core-modules plugin it is located inside the folder of the plugin)

**Comment by radeva** [comment] 2018-09-19 08:34
Closing since the article is updated and the issue is not relevant.

**Closed as completed by radeva** 2018-09-19 08:34 UTC
Labels: help wanted, severity: high, docs
