### ISSUE TITLE
Documentation about authoring custom components is scarce 

### ISSUE THREAD

**Issue by ginev** [NativeScript/docs-v7#696] opened 2017-03-10 15:06 UTC
Feedback coming from this thread: https://github.com/telerik/nativescript-ui-feedback/issues/123

> https://docs.nativescript.org/ui/basics#custom-components This is the only official documentation about the topic that I've found. It's not showing how to pass arguments to the custom components for example. It's not telling anything about event behavior within components. What to consider using contexts, sharing context between components etc. It must be a huge topic if all the amazing features are covered. Right now in my opinion it's just scratching the surface and that's what could and should be improved because it's a really critical topic when going the plain JS / TS route.
{NS} is extremely powerful. I'm really excited about it and am thankful to be able to use it. I'm just trying to say that for me the most important upcoming feature would be improved documentation that goes into much greater detail.

**Comment by etabakov** [comment] 2018-02-23 16:00
Closing this as duplicate of https://github.com/NativeScript/docs/issues/409

**Closed as completed by etabakov** 2018-02-23 16:00 UTC
Labels: help wanted, docs
